### ISSUE TITLE
Noticed that we're getting bad data!

### ISSUE THREAD

**Issue by danelimjoco** [AguaClara/AguaClara.github.io#34]
@ethan92429
It seems some of the values we're getting are not being caught by the filters we put in place to get rid of extreme values more than three standard deviations away because extremely large values that are removed still contribute to the sum calculations needed to calculate the standard deviations. Basically, very large turbidity values make standard deviations extremely big so our filter is insensitive to other big turbidity values.

In particular, a raw water turbidity of 40984516.34 was recorded for Cuatro Communidades, but there also negative turbidity values as well which is pretty concerning

To try and resolve this issue, we tried running the filter extremes function multiple times and that did result in better looking graphs that filtered both the extremely high values as well as the high values. However, we opted not to keep the multiple filters because doing so would make us insensitive to poor data coming in. In other words, we wouldn't be able to tell that extremely large data was being inputted by the operators if we kept filtering them out. We'd like to discuss at the next meeting what we should do about this issue and decide if we want a "management" graph, as well as a graph for the public to view.

**Comment by eak24** [comment]
@danelimjoco I wonder why that extremely high value was recorded? We need to catch these errors at the time they are recorded by the operator so that we can let the operator know of their mistake. We already have the little popup, which I thought would be sufficient, but now I'm starting to think that we should require the operator to explain the reason behind the high turbidity any time they enter a turbidity outside the range we specified.  

I propose we make them write a small explanation. We'd do that by including a conditional question in the form that would only be shown if the turbidity entered was too high, and they clicked through the acknowledgment warning.

I think that filtering out values in our database is not the optimum strategy here - we want to show high values if indeed the operator knowingly submitted them. Maybe their answer to the proposed 'why' question will help us understand. @jacuerp do you think that would be a reasonable thing to add to the next version of the form?

**Comment by jacuerp** [comment]
@ethan92429 @danelimjoco 
If you look at the data surrounding the 40984516.34 value, it seems like it was meant to be separate readings of 4.098 and 4.516. We also got a reading of 4027 in the same time span which seems like it's also missing a period. 

I agree, filtering out values isn't the best course of action since it's very easy for an automated process to remove real outliers instead of just erroneous submissions. It also feels a little bit like lying. And it also hides the underlying problem with our data collection methods.

I think requiring an explanation is a great idea. We also plan to change the filter function to simply exclude values that are above the maximum turbidimeter output of 1100 NTU.

**Comment by eak24** [comment]
Our solution is to require an explanation of abnormal values at the point of collection. We think that blanket data screening (for anything but extreme values is dishonest)
