### ISSUE TITLE
Find and implement MVC framework

### ISSUE THREAD

**Issue by eak24** [AguaClara/AguaClara.github.io#41]
We have been missing an MVC framework. Our implementation falls far behind in that we rely on directly interacting with the localStorage, we have disorganized file structure, and we couldn't even add users if we wanted to. In my searches I've found [ToDoMVC](https://github.com/tastejs/todomvc) a curated site that helps compare the various MVC options with an identical app built in each popular MVC framework. My conclusion (as an unexperienced front-end coder) is that we should be using Angular 2, an MVC framework supported by Google, and one of the most popular MVCs on the web. With this, we could easily implement users, components, custom data views, etc. @fawnwong which MVC do you prefer? Do you have experience with writing for an MVC?

**Comment by fawnwong** [comment]
I only have experience working with MVC in certain course projects, so not in a full-stack application. I have dabbled a little in Angular, however, and know that it's used widely in the industry so it'll be useful to learn. I am very supportive of implementing an MVC framework, Angular or not, as it'll help make everything much more clear for everyone. I'll look around a little more for other options, but otherwise Angular 2 is fine with me.

How difficult do you think it'll be to implement it? I do think it is necessary, but would a large percentage of our code have to be refactored?

**Comment by eak24** [comment]
We started the angular site to address this.
